name: cumulonimbus
summary: Cumulonimbus - A simple, beautiful podcast app.
description: |
  Cumulonimbus is very much a work in progress. Please expect bugs.
grade: stable
confinement: strict
adopt-info: cumulonimbus
architectures:
  - build-on: amd64
  
parts:
  cumulonimbus:
    plugin: nil
    override-build: |
      set -x
      snapcraftctl build
      # Get the latest releases json
      echo "Get GitHub releases..."
      wget --quiet https://api.github.com/repos/z-------------/cumulonimbus/releases -O releases.json
      # Get the version from the tag_name and the download URL.
      VERSION=$(jq . releases.json | grep tag_name | cut -d'"' -f4 | sed s'/v//' | head -n 1)
      DEB_URL=$(grep browser_download releases.json | grep "${VERSION}" | grep deb | cut -d'"' -f4)
      DEB=$(basename "${DEB_URL}")
      echo "Downloading ${DEB_URL}..."
      wget --quiet "${DEB_URL}" -O "${SNAPCRAFT_PART_INSTALL}/${DEB}"
      echo "Unpacking ${DEB}..."
      dpkg -x "${SNAPCRAFT_PART_INSTALL}/${DEB}" ${SNAPCRAFT_PART_INSTALL}
      rm -f releases.json 2>/dev/null
      rm -f "${SNAPCRAFT_PART_INSTALL}/${DEB}" 2>/dev/null
      snapcraftctl set-version "$VERSION"
    after:
      - desktop-gtk2
    build-packages:
      - dpkg
      - jq
      - wget
    stage-packages:
      - libasound2
      - libgconf2-4
      - libgl1-mesa-glx
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxss1
      - libxtst6

apps:
  cumulonimbus:
    command: bin/desktop-launch $SNAP/opt/CPod/cumulonimbus
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - bluez
      - browser-support
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - opengl
      - pulseaudio
      - unity7
      - wayland
      - x11
