name: cumulonimbus
title: CPod
summary: A simple, beautiful podcast app.
description: |
  Simple podcast app built with Electron. Play your favorite podcasts, and discover new ones with an easy to use interface.

  - Listen to our favorite podcasts
  - Search for podcasts and subscribe directly from the app
  - Add episodes to playlists
  - Filter episodes by their duration and release date
  - Export/import podcasts (.opml)

  NOTE: CPod is not actively maintained. Please expect bugs.

  **Authors**

  This snap package is maintained by the Snapcrafters community. It is not necessarily endorsed or officially maintained by the developers of the application itself.  
license: Apache-2.0
website: https://github.com/z-------------/CPod
contact: https://github.com/snapcrafters/cumulonimbus/issues
issues: https://github.com/snapcrafters/cumulonimbus/issues
source-code: https://github.com/snapcrafters/cumulonimbus
icon: snap/gui/cumulonimbus.png
version: '1.28.2'

grade: stable
confinement: strict
architectures:
  - build-on: amd64
base: core22

parts:
  cpod:
    plugin: nil
    override-build: |
      set -xeu
      craftctl default
      # Get the latest releases json
      echo "Get GitHub releases..."
      wget --quiet https://api.github.com/repos/z-------------/CPod/releases -O releases.json
      # Get the version from the tag_name and the download URL.
      VERSION=$(jq . releases.json | grep tag_name | cut -d'"' -f4 | sed s'/v//' | head -n 1)
      DEB_URL=$(grep browser_download releases.json | grep "${VERSION}" | grep deb | cut -d'"' -f4)
      echo "Downloading ${DEB_URL}..."
      wget --quiet "${DEB_URL}" -O cpod.deb
      echo "Unpacking cpod.deb..."
      dpkg -x cpod.deb ${CRAFT_PART_INSTALL}
      rm cpod.deb releases.json
      sed -i 's|Icon=cpod|Icon=${SNAP}/usr/share/icons/hicolor/512x512/apps/cpod.png|' $CRAFT_PART_INSTALL/usr/share/applications/cpod.desktop
    build-packages:
      - dpkg
      - jq
      - wget
    stage-packages:
      - libnspr4
      - libnss3
      - libxss1
      - libxtst6
      - libgconf-2-4

  cleanup:
    after: [cpod]
    plugin: nil
    build-snaps: [gnome-42-2204]
    override-prime: |
      set -eux
      cd /snap/gnome-42-2204/current
      find . -type f,l -exec rm -f $CRAFT_PRIME/{} \;
      for CRUFT in bug lintian man; do
        rm -rf $CRAFT_PRIME/usr/share/$CRUFT
      done
      find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete

apps:
  cumulonimbus:
    extensions: [gnome]
    command: opt/CPod/cpod
    desktop: usr/share/applications/cpod.desktop
    plugs:
      - bluez
      - browser-support
      - gsettings
      - home
      - mount-observe
      - network
      - opengl
      - audio-playback
